gems: [jekyll-paginate, jekyll-gist]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Make money while you work
tagline:             Work on something you enjoy, find someone to pay you for it
url:                 http://makemoneywhileyouwork.com
paginate:            1
baseurl:             "http://songproducer.github.com/nefarious-capsicum"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Leo Treasure
  url:               https://twitter.com/songproducer
  email:             leotreasure@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/songproducer/nefarious-capsicum
